---
title: "MAGs"
author: "Emma Bell"
date: "2023-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r MAG data}

# Taxonomy - GTDB
# Read in the GTDB output files for each sample. Header = (TRUE or FALSE), separator = tab
gtdb_bac_KR46_May <- read.csv("../../../05_Annotation/gtdb/KR46_May/KR46_May.bac120.summary.tsv", header = T, sep = "\t")
gtdb_arc_KR46_May <- read.csv("../../../05_Annotation/gtdb/KR46_May/KR46_May.ar53.summary.tsv", header = T, sep = "\t")
gtdb_bac_KR46_June <- read.csv("../../../05_Annotation/gtdb/KR46_June/KR46_June.bac120.summary.tsv", header = T, sep = "\t")
gtdb_arc_KR46_June <- read.csv("../../../05_Annotation/gtdb/KR46_June/KR46_June.ar53.summary.tsv", header = T, sep = "\t")
gtdb_bac_KR46_Sept <- read.csv("../../../05_Annotation/gtdb/KR46_Sept/KR46_Sept.bac120.summary.tsv", header = T, sep = "\t")
gtdb_arc_KR46_Sept <- read.csv("../../../05_Annotation/gtdb/KR46_Sept/KR46_Sept.ar53.summary.tsv", header = T, sep = "\t")

# Join the output files into one table (rbind = row binding)
gtdb_tab <- rbind(gtdb_arc_KR46_June, gtdb_arc_KR46_May, gtdb_arc_KR46_Sept, gtdb_bac_KR46_June, gtdb_bac_KR46_May, gtdb_bac_KR46_Sept)

# Select the columns with genome and taxonomy
gtdb_tax <-
  gtdb_tab %>%
  select(user_genome, classification) %>%
  rename(genome = user_genome) %>%
  separate(classification, sep = ";", into = c("domain", "phylum", "class", "order", "family", "genus", "species"), remove = F)

# Representative MAGs - dRep
Wdb <- read.csv("../../../06_Representative_MAGs/drep/out/data_tables/Wdb.csv", header = T, sep = ",")
Cdb <- read.csv("../../../06_Representative_MAGs/drep/out/data_tables/Cdb.csv", header = T, sep = ",")
genomeInfo <- read.csv("../../../06_Representative_MAGs/drep/out/data_tables/genomeInfo.csv", header = T, sep = ",")

Rep_bins <- 
  Wdb %>%
  mutate(genome = str_remove(genome, ".fa"))

Cdb_tab <- 
  Cdb %>%
  mutate(genome = str_remove(genome,".fa")) %>%
  select(genome, secondary_cluster)

BinQ_tab <-
  genomeInfo %>%
  mutate(genome = str_remove(genome, ".fa"))

# Relative abundance
CoverM <- read.csv("../../../06_Representative_MAGs/coverm/coverm_drep_mag_rel_abun.tsv", header = T, sep = "\t")
colnames(CoverM)[1]="genome"
colnames(CoverM)[2]="KR46_June"
colnames(CoverM)[3]="KR46_May"
colnames(CoverM)[4]="KR46_Sept"

MAG_summary <-
  left_join(Cdb_tab, BinQ_tab, "genome") %>%
  left_join(., gtdb_tax, "genome")

MAG_rep_summary <- 
  left_join(Rep_bins, BinQ_tab, "genome") %>%
  left_join(., gtdb_tax, "genome") %>%
  left_join(., CoverM, "genome")
```

```{r Abundance plots}
# Plotting abundance data

colnames(MAG_rep_summary)

MAG_rep_summary_l <-
  MAG_rep_summary %>%
  pivot_longer(KR46_June:KR46_Sept, names_to = "sample", values_to = "abundance")

# Example of wide format
MAG_rep_summary %>% select(genome, KR46_May, KR46_June, KR46_Sept)

# Example of long format
MAG_rep_summary_l %>% select(genome, sample, abundance)

# Stacked bar plot
ggplot(MAG_rep_summary_l, aes(x = sample, y = abundance, fill = genus)) +
  geom_bar(stat = "identity")

# Bubble plot
MAG_rep_summary_l %>%
  ggplot(aes(x = sample, y = genome, size = abundance, fill = phylum)) +
  geom_point(shape = 21, alpha = 1)

# I want my samples to be in the right order
MAG_rep_summary_l$sample <- factor(MAG_rep_summary_l$sample, levels = c("KR46_May", "KR46_June", "KR46_Sept"))

# Use facet grid
MAG_rep_summary_l %>%
  ggplot(aes(x = sample, y = genome, size = abundance, fill = phylum)) +
  geom_point(shape = 21, alpha = 1) +
  scale_size_area(max_size = 10) +
  facet_grid(rows = vars(phylum), scales = "free", space = "free") +
  theme(strip.text.y = element_text(colour = NA),
        strip.background.y = element_blank())

# Reorder by another variable
MAG_rep_summary_l %>%
  mutate(genome = fct_reorder(genome, desc(phylum))) %>%
  ggplot(aes(x = sample, y = genome, size = abundance, fill = phylum)) +
  geom_point(shape = 21, alpha = 1) +
  scale_size_area(max_size = 10)

# Change the theme
MAG_rep_summary_l %>%
  mutate(genome = fct_reorder(genome, desc(phylum))) %>%
  ggplot(aes(x = sample, y = genome, size = abundance, fill = phylum)) +
  geom_point(shape = 21, alpha = 1) +
  scale_size_area(max_size = 20) +
  theme_linedraw()

```

